// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "../src/YieldEndowment.sol";
import "../src/mocks/MockERC20.sol";
import "../src/mocks/MockAToken.sol";
import "../src/mocks/MockAavePool.sol";

contract YieldEndowmentTest is Test {
    YieldEndowment public endowment;
    MockERC20 public usdc;
    MockAToken public aUsdc;
    MockAavePool public pool;

    address public owner = address(1);
    address public beneficiary = address(2);
    address public donor1 = address(3);
    address public donor2 = address(4);
    address public newBeneficiary = address(5);

    uint256 public constant INITIAL_BALANCE = 10_000 * 1e6; // 10,000 USDC (6 decimals)

    function setUp() public {
        vm.startPrank(owner);

        // Deploy Mock USDC (6 decimals)
        usdc = new MockERC20("USD Coin", "USDC", 6);

        // Deploy Mock aUSDC
        aUsdc = new MockAToken("Aave USDC", "aUSDC", 6, address(usdc));

        // Deploy Mock Aave Pool
        pool = new MockAavePool(address(usdc), address(aUsdc));

        // Deploy YieldEndowment contract
        endowment = new YieldEndowment(
            address(pool),
            address(usdc),
            address(aUsdc),
            beneficiary
        );

        vm.stopPrank();

        // Mint USDC for test donors
        usdc.mint(donor1, INITIAL_BALANCE);
        usdc.mint(donor2, INITIAL_BALANCE);

        // Approve endowment contract
        vm.prank(donor1);
        usdc.approve(address(endowment), type(uint256).max);

        vm.prank(donor2);
        usdc.approve(address(endowment), type(uint256).max);
    }

    function test_InitialState() public view {
        assertEq(endowment.owner(), owner);
        assertEq(endowment.beneficiary(), beneficiary);
        assertEq(address(endowment.aavePool()), address(pool));
        assertEq(address(endowment.underlyingAsset()), address(usdc));
        assertEq(address(endowment.aToken()), address(aUsdc));
        assertEq(endowment.totalPrincipal(), 0);
        assertEq(endowment.getAccruedYield(), 0);
    }

    function test_Deposit() public {
        uint256 depositAmount = 1_000 * 1e6;

        vm.prank(donor1);
        endowment.deposit(depositAmount);

        assertEq(endowment.totalPrincipal(), depositAmount);
        assertEq(endowment.getDonorPrincipal(donor1), depositAmount);
        assertEq(endowment.donorCount(), 1);
        assertEq(aUsdc.balanceOf(address(endowment)), depositAmount);
        assertEq(usdc.balanceOf(donor1), INITIAL_BALANCE - depositAmount);
    }

    function test_YieldAccrualAndHarvest() public {
        uint256 depositAmount = 1_000 * 1e6;

        vm.prank(donor1);
        endowment.deposit(depositAmount);

        // Simulate 50 USDC of yield generated by Aave pool
        uint256 yieldGenerated = 50 * 1e6;
        pool.simulateYield(address(endowment), yieldGenerated);

        // Check accrued yield
        assertEq(endowment.getAccruedYield(), yieldGenerated);

        // Harvest yield
        uint256 beneficiaryBalanceBefore = usdc.balanceOf(beneficiary);
        uint256 harvested = endowment.harvestYield();

        assertEq(harvested, yieldGenerated);
        assertEq(usdc.balanceOf(beneficiary), beneficiaryBalanceBefore + yieldGenerated);
        assertEq(endowment.getAccruedYield(), 0);
        // Donor's principal remains unchanged
        assertEq(endowment.getDonorPrincipal(donor1), depositAmount);
        assertEq(endowment.totalPrincipal(), depositAmount);
    }

    function test_WithdrawPrincipal() public {
        uint256 depositAmount = 1_000 * 1e6;

        vm.prank(donor1);
        endowment.deposit(depositAmount);

        // Simulate yield accrued
        pool.simulateYield(address(endowment), 20 * 1e6);

        // Donor withdraws full principal
        vm.prank(donor1);
        endowment.withdrawPrincipal(depositAmount);

        assertEq(endowment.getDonorPrincipal(donor1), 0);
        assertEq(endowment.totalPrincipal(), 0);
        assertEq(usdc.balanceOf(donor1), INITIAL_BALANCE);

        // Accrued yield should still be available in the contract for campaign
        assertEq(endowment.getAccruedYield(), 20 * 1e6);
    }

    function test_PartialWithdrawal() public {
        uint256 depositAmount = 1_000 * 1e6;

        vm.prank(donor1);
        endowment.deposit(depositAmount);

        // Partial withdraw
        uint256 withdrawAmount = 400 * 1e6;
        vm.prank(donor1);
        endowment.withdrawPrincipal(withdrawAmount);

        assertEq(endowment.getDonorPrincipal(donor1), 600 * 1e6);
        assertEq(endowment.totalPrincipal(), 600 * 1e6);
        assertEq(usdc.balanceOf(donor1), INITIAL_BALANCE - 600 * 1e6);
    }

    function test_RevertOnWithdrawExcess() public {
        uint256 depositAmount = 500 * 1e6;

        vm.prank(donor1);
        endowment.deposit(depositAmount);

        vm.prank(donor1);
        vm.expectRevert(
            abi.encodeWithSelector(
                YieldEndowment.InsufficientPrincipal.selector,
                600 * 1e6,
                500 * 1e6
            )
        );
        endowment.withdrawPrincipal(600 * 1e6);
    }

    function test_RevertOnHarvestNoYield() public {
        uint256 depositAmount = 1_000 * 1e6;

        vm.prank(donor1);
        endowment.deposit(depositAmount);

        vm.expectRevert(YieldEndowment.NoYieldToHarvest.selector);
        endowment.harvestYield();
    }

    function test_PartialHarvest() public {
        uint256 depositAmount = 1_000 * 1e6;

        vm.prank(donor1);
        endowment.deposit(depositAmount);

        // Simulate 100 USDC yield
        pool.simulateYield(address(endowment), 100 * 1e6);

        // Harvest partial yield (30 USDC out of 100 USDC)
        uint256 beneficiaryBalanceBefore = usdc.balanceOf(beneficiary);
        uint256 harvested = endowment.harvestYieldAmount(30 * 1e6);

        assertEq(harvested, 30 * 1e6);
        assertEq(usdc.balanceOf(beneficiary), beneficiaryBalanceBefore + 30 * 1e6);
        // 70 USDC yield should remain
        assertEq(endowment.getAccruedYield(), 70 * 1e6);

        // Attempt to harvest more than available yield (80 USDC > 70 USDC)
        vm.expectRevert(
            abi.encodeWithSelector(
                YieldEndowment.InsufficientYield.selector,
                80 * 1e6,
                70 * 1e6
            )
        );
        endowment.harvestYieldAmount(80 * 1e6);
    }

    function test_SetBeneficiary() public {
        vm.prank(owner);
        endowment.setBeneficiary(newBeneficiary);
        assertEq(endowment.beneficiary(), newBeneficiary);

        // Non-owner cannot update beneficiary
        vm.prank(donor1);
        vm.expectRevert(YieldEndowment.Unauthorized.selector);
        endowment.setBeneficiary(donor1);
    }

    function test_PauseAndUnpause() public {
        vm.prank(owner);
        endowment.togglePause();
        assertTrue(endowment.paused());

        vm.prank(donor1);
        vm.expectRevert(YieldEndowment.ContractPaused.selector);
        endowment.deposit(100 * 1e6);

        vm.prank(owner);
        endowment.togglePause();
        assertFalse(endowment.paused());
    }
}
